\documentclass{article}

\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}

\DeclareMathOperator{\arsinh}{arsinh}

\title{Biomass Function And Osmolyte Balance Based On The Assumption Of Constant Cell Density}
\date{15.5.2020}

\begin{document}

\maketitle

\noindent TDGM- thermodynamics driven growth model\newline
SRGM- self replicator growth model\newline
\newline
\newline
\section{Biomass Function}
\subsection{The Mother Cell}
In order to meaningfully merge the TDGM and the SRGM an adjusted biomass function has to be constructed. This new biomass function cannot work autocatalytic as in the SRGM, as this would conflict the growth dynamic of TDGM. One way to preserve this dynamic is to make the biomass a function of volume, which is an output of the TDGM. The easiest approach is to define a constant density ratio between the cell volume and the biomass.
\begin{equation}
    k_D = \frac{B}{V}
    \label{Def_B_to_V}
\end{equation}
In the TDGM two kinds of volume are considered: osmotic active volume $V_{os}$ and osmotic inactive volume $V_b$.
\begin{equation}
    V = V_{os} + V_b
    \label{Def_V}
\end{equation}

\noindent
$V_b$ corresponds to 'solid' elements of the cell, such as macromolecules. In the TDGM biomass is not explicitly implemented and $V_b$ is just a function of the relaxed cell radius $R_{ref}$. In the merged model biomass will be explicitly included and should then align with the already implemented solid volume. This is ensured by linking biomass and solid volume as
\begin{equation}
    k_b = \frac{B}{V_b}
    \label{Def_B_to_Vb}
\end{equation}
Consequently $V_b$ is no longer a function of $R_ref$. Note that the total cell density in Eq. \ref{Def_B_to_V} must be smaller, than the actual space occupied by the biomass and therefore $k_b > k_D$.\newline
As in the SRGM several types of biomass will be distinguished: \newline
\begin{itemize}
    \item 'basic' biomass $B_N$, which corresponds to the nucleus
    \item 'structural' biomass $B_A$, specifically the cell wall 
    \item 'metabolic' biomass $B_R$, comprising of metabolic enzymes, ribosomes, chaperons and the like
\end{itemize}
In total the biomass is $B = B_N + B_A + B_R$.\newline
For a grown mother the basic biomass is constant, eg. the nucleus of a cell does not grow once the cell is ready. For growing buds the situation is different and the nucleus has to be produced alongside all other cell components. During Budding this will lead to a decrease in the production of metabolic biomass ('internal biomass'), as assumed in the SRGM.\newline
The structural biomass $B_A$ is defined proportional to the already mentioned relaxed radius of $R_{ref}$, which grows by plastic deformation of the cell wall, as opposed to elastic expansion and demands actual incorporation of new cell wall material.
\begin{equation}
    k_A = \frac{B_A}{A_{ref}}
    \label{Def_BA}
\end{equation}
Assuming all biomass has the same density, the parameter $k_A$ can be estimated from the surface $A_{ref}$ and thickness $d$ of the cell wall:
\begin{align}
    B_A &= k_b \cdot V_{wall} \\
    &= k_b \cdot d \cdot A_{ref}
    \label{Def_kA}
\end{align}
Comparing the coefficients of this equation with Eq. \ref{Def_BA} we see that $k_A = k_b*d$.\newline
To derive a function for the metabolic biomass we insert the definitions above to Eq.\ref{Def_B_to_V} 
\begin{align*}
    B &= k_D\left(V_{os} + V_b\right)\\
    B &= k_DV_{os} + \frac{k_D}{k_b}\cdot B \label{eq:1}\\
    B &= \frac{k_D\cdot k_b}{k_b - k_D}\cdot V_{os}\\
\end{align*}
\begin{align}
    B_R &= \frac{k_D\cdot k_b}{k_b - k_D}\cdot V_{os} - B_A - B_N
    \label{Def_BR}\\
    \dot B_R &= \frac{k_D\cdot k_b}{k_b - k_D}\cdot\dot  V_{os} - \dot B_A - \dot B_N
    \label{Def_der_BR}
\end{align}

Remember that $B_A$ is proportional to the surface and $r^2$, whereas $V_{os} \sim r^3$, meaning that large cells have a higher metabolic capacity than small cells.\newline
If we feed Eq. \ref{Def_BR} in Eq. \ref{eq:1}, we get an explicit expression for $V_b$ as a function of $V_{os}$. This fixed relation is due to the dependence of $V_b$ of the biomass and at the same time the assumption of a constant biomass density.
\begin{equation}
    V_b = V_{os}\cdot \frac{k_D}{k_b-k_D}
    \label{Def_Vb_of_Vos}
\end{equation}
It is very helpful, since it allows to  use almost the original equations of the TDGM, avoiding to introduce further complications through biomass/ volume feedbacks. \newline
The total volume from Eq. \ref{Def_V} can now be written as
\begin{align}
    V &= \frac{k_b}{k_b-k_D}\cdot V_{os}
    \label{Def_re_V}
\end{align}
If a spherical cell is assumed, the cell radius $r$ can be written as
\begin{equation}
    r = \left(\frac{3}{4\cdot \pi}\cdot\frac{k_b}{k_b-k_D}\cdot V_{os}\right)^\frac{1}{3}
    \label{Def_r}
\end{equation}
\begin{equation}
    \dot r = \frac{1}{3} \left(\frac{3}{4\cdot \pi}\cdot\frac{k_b}{k_b-k_D}\right)^\frac{1}{3} \frac{\dot V_{os}}{V_{os}^{\frac{2}{3}}} 
\end{equation}


\subsection{The Bud}
In the SRGM the bud is initialized at the end of the G1 phase with a volume zero. Both mother and bud share the same internal biomass and cyclins, only differing in their structural biomass ($B_A^m$ and $B_A^d)$). At the end of the M phase they separate and cell components are distributed according to the ratio of the structural biomass of mother and bud.\newline
In the TDGM the bud is initialized as complete new cell. Mother and bud are only coupled by diffusion terms for osmolytes and water. The TDGM does not work for a cell volume zero, so the bud has to start with a small volume already. This generates an (admittedly) small bit of cell volume, every time a bud is initialized.\newline
The approach of a fixed cell density and volume dependent biomass has similar not necessarily biological but rather model inherent limitations. 
\subsubsection{Lower Bound On The Osmotic Volume}
As is clear from Eq. \ref{Def_BR} there is a lower bound on the cell radius. None of the three types of biomass can take negative values and both sides of the equation have to be greater or equal to zero. Setting the basic biomass to zero the following relation for the minimal possible osmotic volume arises:
\begin{equation}
\frac{k_D\cdot k_b}{k_b - k_D}\cdot V_{os} = B_A
    \label{lw_lim_Vos}
\end{equation}
Using Eq. \ref{Def_kA} we get
\begin{equation*}
    \frac{k_D\cdot k_b}{k_b - k_D}\cdot V_{os} = k_b \cdot d \cdot A_{ref}
\end{equation*}
Assuming a spherical cell shape yields:
\begin{equation}
    A_{ref} &= 4\cdot \pi \cdot R_{ref}^2 
    \label{Def_Aref}\\
\end{equation}
The reference radius $R_{ref}$ is a function of the tugor pressure $\Pi_t$ and the cell radius $r$, defined in Eq. \ref{Def_r}.
\begin{equation}
    R_{ref} = \frac{r}{1 + \Pi_t \cdot r \cdot \frac{1 - \nu}{E \cdot 2 \cdot d}}
    \label{Def_tugorPressure}
\end{equation}
where $E$ is Young's modulus, a measure of the cell wall elasticity, $d$ the already mentioned cell wall thickness and $\nu$ the Poission's ratio. The surface of the relaxed cell (Eq. \ref{Def_Aref}) is then defined as:
\begin{equation}
    A_{ref} = \frac{4\cdot \pi \cdot r^2}{\left(1 + \Pi_t \cdot r \cdot \frac{1 - \nu}{E \cdot 2 \cdot d}\right)^2}
    \label{Def_Aref_from_r}
\end{equation}
Remembering the definition of the cell radius as a function of the osmotic volume (Eq. \ref{Def_r}) and summing everything up in Eq. \ref{lw_lim_Vos} amounts to
\begin{equation*}
    \frac{k_D\cdot k_b}{k_b - k_D}\cdot 
    V_{os} 
    =
    k_b \cdot d \cdot 
    \frac{4\cdot \pi \cdot 
    \left(\left(\frac{3}{4\cdot \pi}\cdot\frac{k_b}{k_b-k_D}\cdot V_{os}\right)^\frac{1}{3}\right)^2}
    {\left(1 + 
    \Pi_t \cdot 
    \left(\frac{3}{4\cdot \pi}\cdot\frac{k_b}{k_b-k_D}\cdot V_{os}\right)^\frac{1}{3} 
    \cdot \frac{1 - \nu}{E \cdot 2 \cdot d}\right)^2}
\end{equation*}
This rather unpleasant inequality defines a lower limit on the osmotic volume and therefor the starting volume of the bud.\newline
Be 
\begin{align*}
    \alpha &= \frac{3}{4\cdot \pi}\cdot\frac{k_b}{k_b-k_D}\\
    \beta &= \frac{1 - \nu}{E \cdot 2 \cdot d}
\end{align*}
where by knowledge of the range of $E, d, \nu$ we know already:
\begin{align}
    \beta << 1
    \label{ineq:approx_beta}
\end{align}
\begin{align*}
    &\frac{k_D\cdot k_b}{k_b - k_D}\cdot 
    V_{os} 
    = 
    k_b \cdot d \cdot 
    \frac{4\cdot \pi \cdot 
    \left(\alpha\cdot V_{os}\right)^\frac{2}{3}}
    {\left(1 + 
    \Pi_t \cdot 
    \left(\alpha\cdot V_{os}\right)^\frac{1}{3} 
    \cdot \beta\right)^2}
    \\
    &\frac{k_D}{k_b - k_D}
    = 
    \frac{4\cdot \pi \cdot d\cdot 
    \alpha^\frac{2}{3}}
    {V_{os}^\frac{1}{3} + 
    2 \Pi_t\beta \cdot 
    \alpha  
    ^\frac{1}{3}\cdot V_{os}^\frac{2}{3}
    +
    \Pi_t^2\beta \cdot 
    \alpha  
    ^\frac{2}{3}\cdot V_{os}}
    \\
    &V_{os}^\frac{1}{3} + 
    2 \Pi_t\beta \cdot 
    \alpha  
    ^\frac{1}{3}\cdot V_{os}^\frac{2}{3}
    +
    \Pi_t^2\beta \cdot 
    \alpha  
    ^\frac{2}{3}\cdot V_{os}
    =
    \frac{4\cdot \pi \cdot d\cdot \left(k_b - k_D\right)\cdot 
    \alpha^\frac{2}{3}}
    {k_D}
    \\
    &V_{os}^3
    +
    \left(\frac{2}{\Pi_t\cdot \alpha  
    ^\frac{1}{3}}\right)^3\cdot V_{os}^2
    +
    \left(\frac{1}{\Pi_t^2\cdot \beta \cdot \alpha  
    ^\frac{2}{3}}\right)^3\cdot V_{os}
    -
    \left(\frac{4\cdot \pi \cdot d\cdot \left(k_b - k_D\right)}
    {k_D\cdot \Pi_t^2\cdot \beta}\right)^3
    = 
    0
\end{align*}
Be 
\begin{align*}
    a &=\left(\frac{2}{\Pi_t\cdot \alpha  
    ^\frac{1}{3}}\right)^3 \\
    b &= \left(\frac{1}{\Pi_t^2\cdot \beta \cdot \alpha  
    ^\frac{2}{3}}\right)^3 \\
    c &= -\left(\frac{4\cdot \pi \cdot d\cdot \left(k_b - k_D\right)}
    {k_D\cdot \Pi_t^2\cdot \beta}\right)^3
    \label{sub_abc}
\end{align*}
Now the following equality will be solved to find the minimal possible $V_{os}$:
\begin{equation*}
    V_{os}^3 + a\cdot V_{os}^2 + b\cdot V_{os} + c = 0
\end{equation*}
With 
\begin{align*}
    x &= V_{os} - \frac{a}{3}\\
    p &= b - \frac{a^2}{3}\\
    q &= \frac{2a^3}{27}-\frac{ab}{3} + c
    \label{sub_xpq}
\end{align*}
this equation can be transformed to the depressed cubic equation
\begin{equation*}
    x^3 + p\cdot x + q = 0
\end{equation*}
Important for the solution of this equation is the discriminant $\Delta := \left(\frac{q}{2}\right)^2 + \left(\frac{p}{3}\right)^3$ and whether it is positive or negative. The first term is quadratic hence always positive. The second term is non negative for $b \geq \frac{a^2}{3}$. Looking at the definition of $a$ and $b$ this means:
\begin{equation*}
    3\cdot\left(\frac{1}{\Pi_t^2\cdot \beta \cdot \alpha  
    ^\frac{2}{3}}\right)^3 \geq \left(\frac{4}{\Pi_t^2\cdot \alpha  
    ^\frac{2}{3}}\right)^3
\end{equation*}
As stated above in (\ref{ineq:approx_beta}) $\beta << 1$ for the parameter range of interest. Consequently $b \geq \frac{a^2}{3}$ is true and p and the discriminant are positive. There is only one solution, which is real as well:
\begin{equation}
    V_{os}^{min} = \frac{1}{3}\left(2\sqrt{3b - a^2}\cdot \sinh{\mu} - a\right)
    \label{eq:sol_min_Vos}
\end{equation}
where
\begin{equation*}
    \mu = \frac{1}{3}\arsinh{\left(-\frac{q}{2}\sqrt{\frac{27}{p^3}}\right)}
\end{equation*}
This is the smallest osmotic volume, that satisfies the assumption of a constant cell density. As defined earlier ${p,q,a,b}$ are functions of the fixed parameter set ${k_b,k_D,\nu,E,d}$ and $\Pi_t$, which is in a quasi steady state around the critical tugor pressure $\Pi_{tc}$, where plastic expansion of the radius takes place.

\subsubsection{Upper Bound On The Increase Of Basic Biomass}
During bud growth the change in basic biomass $\dot B_N$ is not zero. A similar relation as Eq. \ref{lw_lim_Vos} with regard to an upper limit of $\dot B_N$ can be formulated, such that $\dot B_R$ does not become negative. With this requirement and the definition of $\dot B_R$ (Eq. \ref{Def_der_BR}) it holds that
\begin{equation}
    \frac{k_D\cdot k_b}{k_b-k_D}\cdot \dot V_{os} - \dot B_A \geq \dot B_N
    \label{up_lim_dBN}
\end{equation}
This inequality is no longer analytically solvable, since $\dot B_{A} :=  \dot B_{A}(\dot R_{ref})$, where $\dot R_{ref}$ is dependent on the numerically determined plastic expansion.  \newline
Ineq. \ref{up_lim_dBN} can still be used to define an adaptive production of basic biomass. Be $k_N \in [\,0,1]\,$, setting the ratio of metabolic and basic biomass production and 
\begin{equation*}
    \Delta_{\dot B}:=\frac{k_D\cdot k_b}{k_b-k_D}\cdot \dot V_{os} - \dot B_A
\end{equation*}
Then an adaptive $\dot B_N$ can be defined as
\begin{equation}
    \dot B_N = k_N\cdot \Delta_{\dot B}
    \label{Def_dBN}
\end{equation}

\section{Osmolyte Balance}
An important aspect of the TDGM is the balance of osmolytes. Their uptake is proportional to the surface and the consumption is proportional to the volume. As the cell is growing, an additional dilution term is introduced. The consumption of osmolytes being proportional to cell volume cannot really account for the costs of cell growth, but is better understood as a maintenance cost: proteins degrade and have to be reproduced, signalling and inner cellular transport need energy etc. Would it reflect the costs of growth, it had to decrease as the cell volume saturates. The way the TDGM is implemented right now, this would lead to an increase in omsolyte concentration and therefor again more  growth.\newline
A short calculation shows, that maintenance costs due to Biomass degradation can indeed be approximated as proportional to cell volume, assuming a first order degradation kinetic and constant biomass to volume ratio (Eq. \ref{Def_B_to_V}):
\begin{align*}
    \dot B_{deg} &= k_{deg}\cdot B \\
                 &= k_{deg}\cdot k_D\cdot V\\
    \dot n_{main} &= k_{cost} \cdot B_{deg}\\
                  &= k_{cost} \cdot k_{deg}\cdot k_D\cdot V
\end{align*}
where $k_{deg}$ is the degradation constant, $k_{cost}$ the number of osmolyte molecules consumed per unit of produced biomass and $\dot n_{main}$ the number of osmolyte molecules consumed per time due to reproduction of degraded biomass. The constants $k_{cost}$, $k_{deg}$ and $k_D$ can be summed up in one as $k_{main}$. This is equivalent to the $k_{cons}$ in the TDGM.\newline
To quantify the cost of biomass production a new term is needed. As stated before biomass and volume are assumed to be proportional (Eq. \ref{Def_B_to_V}). The change in biomass as a function of the volume then is
\begin{equation}
    \dot B = k_D \cdot \dot V
    \label{eq:t_deriv_B}
\end{equation}
The cost of this amounts to
\begin{align*}
    \dot n_{cost} &= k_{cost} \cdot \dot B\\
                  &= k_{cost} \cdot k_D \cdot \dot V
\end{align*}
The complete equation for the osmolyte balance is
\begin{align}
    \dot c &= \frac{\dot n_{up}}{V} - \frac{\dot n_{main}}{V} - \frac{n_{cost}}{V} - \dot c_{dilu}\\
           &= k_{up}\cdot \frac{A}{V} - k_{main} - \left(k_{cost}\cdot k_D - c\right)\cdot \frac{\dot V}{V}\\
\end{align}
This is the same equation as in the TDGM besides a production cost term, which is very similar to the dilution term. It only adds a constant to the already almost constant concentration. This extra term does not change the fundamental behaviour of the system, but only slows down the growth of the cell. The final radius of the cell is untouched by it and remains $r_{final} = 3\frac{k_{up}}{k_{main}}$.

\end{document}


