The general equation for the change of concentration of a protein $\left(\frac{P}{V}\right)$ in a growing cell cann be written as:
\begin{equation}
  \frac{d}{dt}\left(\frac{P}{V}\right) = \frac{1}{V}\cdot \frac{d}{dt}P - \frac{P}{V^2}\cdot\frac{d}{dt}V
\end{equation}
The change in absolute molecule number can be obtained using the first term. Assuming a second order kinetic with reactants \textit{mRNA} and $B$ representing biosynthetic biomass and a first order degradation it follows
\begin{equation}
  \frac{1}{V}\cdot \frac{d}{dt}P = k_p\cdot \frac{mRNA}{V}\cdot \frac{B}{V} - k_d\cdot \frac{P}{V}
\end{equation}
multiplied with the cell volume:
\begin{equation}
  \frac{d}{dt}P = k_p\cdot mRNA\cdot \frac{B}{V} - k_d\cdot P
\end{equation}
\noindent
In order to maintain  concentration homeostasis of proteins and mRNA in growing cells
\begin{itemize}
  \item protein translation per mRNA has to increase
  \item mRNA transcription per gene copy has to increase
\end{itemize}
Without directly mentioning it, the first assumption is already made in the BGM, by assuming the second order kinetic with the biomass as a reactant of the mRNA. The same number of mRNA molecules yields a higher protein production, when the internal biomass increases. \newline
The second assumption is not included and mRNA numbers are volume independent. This leads to dilution of mRNA. Also since the ratio $\frac{B}{V}$ is decreasing in the growing cell protein concentrations decrease aswell. In the BGM this has no effect, because the thresholds for phase transition are defined for absolute molecule number, which of course increase. 





