\section{Cyclin expression}

The general equation for the change of concentration of a protein $\left(\frac{P}{V}\right)$ in a growing cell cann be written as:
\begin{equation}
  \frac{d}{dt}\left(\frac{P}{V}\right) = \frac{1}{V}\cdot \frac{d}{dt}P - \frac{P}{V^2}\cdot\frac{d}{dt}V
\end{equation}
The change in absolute molecule number can be obtained using the first term . \newline
In the BGM a second order kinetic with reactants \textit{mRNA} and $B$ representing biosynthetic biomass is assumed. This implies an increase in translated protein per copy number of mRNA with increasing metabolic biomass. Including a first order degradation as well it follows that
\begin{equation}
  \frac{1}{V}\cdot \frac{d}{dt}P = k_p\cdot \frac{mRNA}{V}\cdot \frac{B}{V} - k_d\cdot \frac{P}{V}
\end{equation}
Multiplied with the cell volume:
\begin{equation}
  \frac{d}{dt}P = k_p\cdot mRNA\cdot \frac{B}{V} - k_d\cdot P
\end{equation}
\noindent
Previous studies have emphasized the need and evidence for a scaling of copy number of mRNA per gene site with cell volume/biomass (Lin,Amir 2018;Sun,Bowman et al. 2020). 
In a growing cell constant transcription levels may result in a $\frac{1}{V}$ dilution of the transcriptome and the proteome. \newline
As shown for the BGM in the analysis section this happens indeed.
Consequently if the cyclin threshold are implemented as concentrations, cells get stuck in the cell cycle when their cyclin concentrations become to low to reach the thresholds. \newline
For the sake of simplicity and comparability with the original model the MGM was implemented with amount based thresholds. Additionally a version with concentration based thresholds. While the probability of a transcription burst remains constant, the transcription rate during a burst scales with cell size, as was proposed in Sun,Bowman et al. 2020\newline
The following results where produced with a variation of the BGM. The $Cln$ threshold is implemented as critical concentration and not as amount. On the population level this still results in size homeostasis (Figure \ref{fig:BGM_ClnThrConc4}). Spießer et al. concluded the implementation of the cyclin thresholds as an absolute amount was not a size sensing mechanism (Cite Spießer 2012 here!!!). This might not be entirely true. It is in fact more of a reverse size sensing mechanism, where big cells stop budding after a few generations. As the cells grow the concentration of cyclins is ever falling (Figure \ref{fig:BGM_ClnDil}) and average G1 durations clearly increase (Figure \ref{fig:BGM_TG1ClnDil}). Also simulations with a concentration based threshold show interesting behavior when this threshold is adjusted, as Figure \ref{fig:BGM_ClnThrConc6} demonstrates.
\begin{figure*}[t!]
  \begin{subfigure}[b]{0.5\textwidth}
    \centering
    \includegraphics[width=6cm,keepaspectratio]{graphics/BGM_ClnThrConc4.pdf}
    \caption{G1 ($Cln$) threshold set to 4}
    \label{fig:BGM_ClnThrConc4}
  \end{subfigure}
  ~
  \begin{subfigure}[b]{0.5\textwidth}
    \centering
    \includegraphics[width=6cm,keepaspectratio]{graphics/BGM_ClnThrConc6.pdf}
    \caption{G1 ($Cln$) threshold set to 6}
    \label{fig:BGM_ClnThrConc6}
  \end{subfigure}
  \caption{Population simulated with concentration based G1 threshold
    ($Cln$). Mean volume and standard deviation plotted. Thin lines belong
    to single cells. Note that older cells stop budding.}
\end{figure*}


\begin{figure}[H]
 \begin{center}
 \includegraphics[width=10cm,keepaspectratio]{graphics/BGM_ClnDil.png}
 \caption{Single cell from population simulated with concentration based G1 threshold ($Cln$) and amount based G2 threshold ($Clb$). Concentration of $mCLN$ and $Cln$ plotted.}
 \label{fig:BGM_ClnDil}
 \end{center}
\end{figure}

\begin{figure}[H]
 \begin{center}
 \includegraphics[width=10cm,keepaspectratio]{graphics/BGM_TG1ClnDil.png}
 \caption{Single cell from population simulated with concentration based G1 threshold ($Cln$) and amount based G2 threshold ($Clb$). Concentration of $mCLN$ and $Cln$ plotted.}
 \label{fig:BGM_TG1ClnDil}
 \end{center}
\end{figure}





