\section{Motivation}
In 2019 Altenburg et al. proposed a model for volume growth of single yeast cells (\textit{s.cerevisiae}) \cite{Altenburg2019} (hereafter VGM).
Their goal was to provide a mechanistic explanation for changes of the cell volume. The model was based on thermodynamic principles,
as opposed to phenomenological descriptions of volume trajectories.
It included external and internal osmolyte concentrations and could accurately reproduce cellular reactions in osmotic shock experiments.
Additionaly an extended version of the model was able to simulate the growth of mother cells and buds.
The simulations where limited to one cell cycle and the duration of the cell cycle phases were fixed.
A natural expansion of the model would be to cover several generations and to introduce an active cell cycle regulation.
This would be an opportunity to test its validity on long time scales and for variable cell phase durations.
\newline
In 2012 Spießer et al. presented a model that provided a framework for cell cycle regulation \cite{Spiesser2012} (hereafter BGM).
It was based on auto catalytically growing cells.
As these cells grew and divided over many generations a large and diverse population formed.
Even though rapid advances are made in the acquisition of single cell data,
a clear understanding of experimental results still is often clouded by measurements over large numbers of cells.
This allows observations only on averaged mean cells and can lead to confusion of individual cell characteristics with emergent properties of the ensemble.
An example is the homeostasis of cell size on the population level, 
whilst single cells do not necessarily stop growing.
The simulation of \textit{in silico} ensembles can help to reproduce such experimental results and shed light on underlying mechanisms.
If the VGM was to succesfully replace the growth module for single cells in the BGM such in silico experiments could be performed for the VGM too.
The inculsion of osmolyte concentrations in the VGM could be used to study the effects of osmotic shocks and variation of the osmolyte concentration of the growth medium on whole populations, 
instead of just single cells.



\section{The cell cycle of yeast}
Many organisms divide symmetrically. 
Budding yeast is unusual in that it divides asymmetrically \cite{November1977}. 
Whilst growing it bulges out and forms a bud.
After some time the bud separates from the parent cell.
In this process all the necessary components, such as the DNA have to be replicated and transferred to the bud.
Cells that bud for the first time are called \textit{daughter} cells.
Older cells are called \textit{mother} cells.
The cycle of growth and division is generally divided in two main phases, the interphase (I), where all growth related processes happen and the mitotic phase (M), where the parent cell and the bud separate.
The interphase is again subdivided into a first gap phase between division and DNA-replication (G1) where only the parent cell grows. 
This is followed by a synthesis phase (S) where,
after passing the start signal (START) at the end of G1, 
DNA-replication and bud formation begin. 
Then comes a second gap phase (G2) where the parent cell and bud continue growing and the duplicated nucleous is transferred to the bud.
\begin{figure}[H]
  \centering
  \includegraphics[width=7cm,keepaspectratio]{graphics/Intro_cellCycle.png}
  \caption{Cell cycle in yeast. Figure taken from \cite{Cui2017}}
  \label{fig:Intro_cellCycle}
\end{figure}

\newline
The progression from one phase to another is controlled by a vast network of signalling proteins.
It culminates in the expression of a cascade of genes at each transition \cite{Noguchi2014}.
Two important protein classes in this network are cyclins and cyclin-dependent-kinases (CDK). 
A kinase is an enzyme that attaches a phosphate group to its substrate, hence drastically changing its biochemical properties. 
In order to be active CDK's need a cyclin to bind to them.
Depending on the binding cyclin they target different substrates \cite{Enserink2010}. 
\newline
Another important class of regulatory proteins is called transcription factors. 
They regulate the activity of genes by binding to strands of DNA.
This changes its morphology and binding sites for RNA-polymerases are inhibited or promoted.
The activity of many transcription factors is regulated by phosphorylation and dephosphorylation \cite{Hunter1992}. 
\newline
Here the cyclins come into play.
When the right cyclin is abundant in sufficient amounts the CDKs target
specific transcription \cite{Enserink2010} factors and the genes for transition to the next cell phase are expressed. \newline
The following simplified description of the network regulating the transition from the G1 phase to the S phase is based on Barber et al. 2020 \cite{Barber2020}.\newline
During the early G1 phase the inhibitor Whi5 is localized in the nucleus of the cell.
There it binds to the transcription factor SBF and inactivates it.
Active SBF induces the transcription of the genes needed for the phase transition. 
The cyclin Cln3 binds to the cyclin dependent kinase Cdk1 and phosphorylates Whi5. 
Phosphrylated Whi5 releases SBF and is exported from the nucleus. 
The now free SBF induces the transcription of several other cyclins, 
Cln1 and Cln2 among the first.
These cyclins further phosphorylate Whi5, 
leading to a positive feedback loop 
and subsequent transition to the S phase.
\begin{figure}[H]
  \centering
  \includegraphics[width=6cm,keepaspectratio]{graphics/Intro_cycleContr.jpg}
  \caption{Schematic representation of the regulation of the G1 phase in yeast. Figure taken from \cite{Barber2020}}
  \label{fig:Intro_cycleContr}
\end{figure}

